dist: trusty
sudo: required
language: bash

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash

install:
  - curl https://raw.githubusercontent.com/RenderQwerty/express_devops-homeworks/master/install-dependencies.sh | sudo bash

script:
  - curl https://raw.githubusercontent.com/RenderQwerty/express_devops-homeworks/master/validate_packer.sh | bash
  - curl https://raw.githubusercontent.com/RenderQwerty/express_devops-homeworks/master/validate_terraform.sh | bash
  - curl https://raw.githubusercontent.com/RenderQwerty/express_devops-homeworks/master/validate_ansible.sh | bash
