---
dependencies: []

galaxy_info:
  author: renderqwerty
  description: mongo database for Ubuntu Trusty
  company: PPL33-35
  license: license (BSD, MIT)
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  galaxy_tags:
    - mongo
