version: '3.3'
services:

  post_db:
    image: "mongo:${mongodb_version:-latest}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
            - comment_db

  ui:
    image: "${USERNAME}/ui:${ui_version:-2.2}"
    ports:
      - "${ui_exposed_web:-9292}:9292/tcp"
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: "${USERNAME}/post:${post_version:-2.2}"
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: "${USERNAME}/comment:${comment_version:-2.2}"
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    external:
      name: frontend
  back_net:
    external:
      name: backend
