---
global:
  scrape_interval: '5s'

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets:
        - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:9292'

  - job_name: 'post'
    static_configs:
      - targets:
        - 'post:5000'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'mongo'
    static_configs:
      - targets:
        - 'mongo_exporter:9216'

  - job_name: 'cloudprober'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'cloudprober:9313'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'cadvisor:8080'

  - job_name: 'docker-native'
    static_configs:
      - targets:
        - 'host:9323'
